require('options.init-first')
require('plugins')
require('treesitter-config')
require('nvim-cmp-config')
require('lsp-config')
require('lualine-config')
require('toggleterm-config')
require('colorizer-config')
require('nvim-tree-config')
require('gitsigns-config')
require('telescope-config')
require('nord-config')
require('commands')
require('keymaps')
require('options.init-last')

